import { Button, Row } from 'react-bootstrap';
import Card from 'react-bootstrap/Card';
import ListGroup from 'react-bootstrap/ListGroup';
import { useDispatch, useSelector } from 'react-redux';
import { showTrivial } from '../store/trivialsSlice';

export default function AiTrivialsCard({ country }) {
  const countryName = country.name.common;
  const countryCode = country.cca3;
  const dispatch = useDispatch();
  const trivialsLoading = useSelector((state) => state.trivials.isLoading);
  const currentTrivial = useSelector((state) => state.trivials.currentTrivial);
  const isInitialized = useSelector((state) => state.trivials.isInitialized);

  return (
    <Row>
      <Card>
        <Card.Body>
          <Card.Title>
            <i className="bi bi-x-diamond-fill me-2"></i>
            Learn more about {countryName} with Open AI
          </Card.Title>
          <Card.Text>
            Click the button to get interesting fact about {countryName}. Generated by OpenAI
          </Card.Text>
        </Card.Body>
        <Card.Body>
          <Button onClick={() => dispatch(showTrivial(countryCode))}>Show fact about {countryName}</Button>
        </Card.Body>
        {isInitialized &&
          <ListGroup className="list-group-flush">
            {!trivialsLoading &&
              <ListGroup.Item>{currentTrivial.fact}</ListGroup.Item>
            }
          </ListGroup>
        }
      </Card>
    </Row>
  );
}
